### ISSUE TITLE
[Improvement] Combination with hydra

### ISSUE THREAD

**Issue by llcc** [mhayashi1120/Emacs-imagex#2]
Hi @mhayashi, 

thanks for your package.
I would like to give you an advice about keybind. I am not sure if know hydra at https://github.com/abo-abo/hydra, another great package for keybind optimization. I think you can improve your binding with it.

**Comment by mhayashi1120** [comment]
Thanks for your information.
I would like to consider it.

**Comment by mhayashi1120** [comment]
hydra is very interesting feature.
I would like to use it.
